### ISSUE TITLE
[FEATURE] better answer format

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/chatrepo#7]
**Is your feature request related to a problem? Please describe.**

Print out a better answer format for query.

**Describe the solution you'd like**

For example: What is eBPF and eunomia-bpf?

> Query: What is eBPF and eunomia-bpf?
>
> Github search results:
> Found 30 results
> [1] Title: [windows] fedml login failed on windows URL: https://github.com/FedML-AI/FedML/issues/775
>    [101] issue: 
> ```
> [windows] fedml login failed on windows
> ```
>
>    URL: https://api.github.com/repositories/378330983/issues/8
> [4] Title: Windows poetry build failures URL: https://github.com/com-posers-pit/smw_music/issues/143
> [5] Title: Windows Compatibility (?) URL: https://github.com/bennm37/image_colourisation/issues/4
> [6] Title: [Bug]: Pbm d'installation sur windows  URL: https://github.com/cnumr/ecoindex_scrap_python/issues/85
> [7] Title: Tensorflow on Windows URL: https://github.com/NLP-Suite/NLP-Suite/issues/1031
> [8] Title: Windows CI keeps failing (flaky) URL: https://github.com/secure-systems-lab/securesystemslib/issues/520
> [9] Title: Windows vanish URL: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2300
> [10] Title: [BUG] File URL on Windows URL: https://github.com/conda/grayskull/issues/448

eBPF (extended Berkeley Packet Filter) is a virtual machine and a set of kernel-level programs that can be used to filter and monitor network traffic. It is a powerful tool for network security and performance monitoring.

eunomia-bpf is an open source project that provides a framework for writing eBPF programs. It provides a set of libraries and tools to help developers write and deploy eBPF programs. It also provides a set of tools for debugging and analyzing eBPF programs.

**Comment by introt** [comment]
Offtopic to the issue: @yunwei37, please use the code block formatting instead of quoting next time to avoid pinging random repositories. Thanks!

**Comment by yunwei37** [comment]
Sorry about that...
